### ISSUE TITLE
Multiple slope files from dataProcessing.py

### ISSUE THREAD

**Issue by maxdudek** [Boyle-Lab/TRACE#11]
Hi,

When I ran the script like this:

```
$TRACE/scripts/dataProcessing.py $PEAKS $BAM $GENOME \
    --genome hg19 \
    --atac-seq pe 
```

I get two slope files, `TRACE_slope_1.txt` and `TRACE_slope_2.txt`. What is the difference between these two, and which one should I use in further steps?

Thanks,
Max

**Comment by aboyle** [comment]
These represent the first and second derivatives for the slopes. We use the second (TRACE_slope_2.txt) for downstream analysis.
