### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by Bek** [Boyle-Lab/TRACE#4]
Is the Dockerfile available? There are issues with installing and linking `gsl` libraries and maybe the Dockerfile would give some hints.

**Comment by OuyangNX** [comment]
You can find the docker file at quay.io/ouyang/trace:version_1
Our C program requires the GNU Scientific Library (GSL). You can download it here: [https://www.gnu.org/software/gsl/](https://www.gnu.org/software/gsl/).

**Comment by Bek** [comment]
I was able to get the Docker image from quay.io and run the TRACE program, thank you. I am curious if you have created the Docker image with a Dockerfile like this: https://github.com/ENCODE-DCC/atac-seq-pipeline/blob/master/dev/docker_image/Dockerfile. I am trying to build the program on a new Ubuntu machine but getting these errors below. I was curious how the `gsl` was installed and linked in the Docker image.


        `(TRACE_env) ubuntu@ip-172-31-20-22:~/TRACE$ make
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/esthmm.o src/esthmm.c
        src/esthmm.c: In function ‘main’:
        src/esthmm.c:203:21: warning: too many arguments for format [-Wformat-extra-args]
             fprintf(stderr, "Error: required files not provided \n", seqfile);
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/BaumWelch.o src/BaumWelch.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/nrutil.o src/nrutil.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/hmmutils.o src/hmmutils.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/emutils.o src/emutils.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/logmath.o src/logmath.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/fwd_bwd.o src/fwd_bwd.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/viterbi.o src/viterbi.c
        gcc -lgsl -lgslcblas -fopenmp -DNDEBUG -D_FORTIFY_SOURCE=2 -O2  -c -o src/fileutils.o src/fileutils.c
        gcc -lgslcblas -lgsl -fopenmp -o TRACE src/esthmm.o src/nrutil.o \
            src/emutils.o src/hmmutils.o src/logmath.o src/fwd_bwd.o \
            src/BaumWelch.o src/viterbi.o src/fileutils.o -lm
        src/esthmm.o: In function `main':
        esthmm.c:(.text.startup+0x43c): undefined reference to `gsl_vector_alloc'
        esthmm.c:(.text.startup+0x491): undefined reference to `gsl_vector_alloc'
        esthmm.c:(.text.startup+0x5c3): undefined reference to `gsl_matrix_alloc'
        esthmm.c:(.text.startup+0x605): undefined reference to `gsl_vector_alloc'
        esthmm.c:(.text.startup+0x644): undefined reference to `gsl_matrix_get_row'
        `

**Comment by OuyangNX** [comment]
Yes I created the Docker image with a Dockerfile like the file in that link. GSL library installation is in Dockerfile but not in `environment.yml`. If you run TRACE using Docker image, it should install all required libraries and build TRACE for you. If you run Makefile after creating the Conda environment, you will need to install GSL library manually. You can try `sudo apt-get install libgsl-dev` to install it.
